[tool.ruff]
# Specify which rules to enable. Common ones include:
# E - Pycodestyle errors
# F - Pyflakes errors
# W - Pycodestyle warnings
# C90 - McCabe complexity plugin
select = ["E", "F", "W", "C90", "I"]

# Exclude specific files or directories (e.g., migrations, static files)
exclude = ["migrations", "static", "venv", "env", "settings", "__init__.py"]

# Set the maximum line length (if not ignoring E501)
line-length = 120

src = ["backend"]

# Enable or disable fixable linting issues automatically
fix = true

# Ignore specific errors
# ignore = ["D105"]

[tool.ruff.lint.isort]
combine-as-imports = true



[tool.pytest.ini_options]
minversion = "6.0"
django_settings_module = "core.settings.test"
