version: "3.8"

services:
  backend:
    build: .
    container_name: backend
    command: ["/app/wait-for-it.sh", "db:5432", "--", "gunicorn", "myproject.wsgi:application", "--bind", "0.0.0.0:8000"]
    env_file:
      - .env.prod
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    depends_on:
      - my-postgres
    networks:
      - django_network

  my-postgres:
    container_name: pgdb
    image: postgres:15-bullseye
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - django_network

    nginx:
      image: nginx
      container_name: nginx
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - static_volume:/home/app/static
        - media_volume:/home/app/media
      depends_on:
        - backend

volumes:
  static_volume:
  media_volume:
  postgres_data:

networks:
  django_network:
