version: "3.9"

services:
  backend:
    build: . 
    container_name: dg_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app 
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
    depends_on:
      - my-postgres

  my-postgres:
    container_name: pgdb
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword