version: "3.9"

services:
  backend:
    build: . 
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app 
    ports:
      - "8000:8000"
    # environment: #! use this if you want to using (python-decouple) : https://pypi.org/project/python-decouple/
    #   - SECRET_KEY=test
    #   - DEBUG=True