version: "3.8"

services:
  backend:
    build: . 
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app  
    ports:
      - "8000:8000"
    depends_on:
      - my-postgres
    networks:
      - django_network

  my-postgres:
    container_name: pgdb
    image: postgres:15-bullseye
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network: