# Generated by Django 4.2 on 2024-06-19 04:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='نام نویسنده')),
            ],
            options={
                'abstract': False,
                'order_with_respect_to': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, help_text='کاربران از طریق این لینک به صفحه دسته بندی مورد نظر دسترسی پیدا خواهند کرد', unique=True, verbose_name='لینک دسترسی')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته بندی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='handout.category')),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, help_text='کاربران از طریق این لینک به صفحه تگ مورد نظر دسترسی پیدا خواهند کرد', unique=True, verbose_name='لینک دسترسی')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='نام تگ')),
            ],
            options={
                'verbose_name_plural': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Handout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, help_text='کاربران از طریق این لینک به صفحه جزوه دسترسی پیدا خواهند کرد', unique=True, verbose_name='لینک دسترسی')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام جزوه')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('file_name', models.CharField(max_length=150, verbose_name='نام فایل')),
                ('page_count', models.PositiveIntegerField(verbose_name='تعداد صفحات جزوه')),
                ('file_size', models.PositiveIntegerField(verbose_name='اندازه فایل')),
                ('visit_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('publish_time', models.DateField(verbose_name='تاریخ انتشار')),
                ('file', models.FileField(upload_to='uploads/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>', verbose_name='آپلود فایل')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='handout.author', verbose_name='نویسنده')),
                ('category', models.ManyToManyField(blank=True, null=True, to='handout.category', verbose_name='دسته بندی')),
                ('tag', models.ManyToManyField(blank=True, null=True, to='handout.tag', verbose_name='تگ')),
            ],
            options={
                'verbose_name_plural': 'Handout',
            },
        ),
    ]
