# Generated by Django 4.2 on 2024-06-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handout',
            name='category',
            field=models.ManyToManyField(blank=True, to='handout.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='tag',
            field=models.ManyToManyField(blank=True, to='handout.tag', verbose_name='تگ'),
        ),
    ]
