# Generated by Django 4.2 on 2024-06-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handout', '0002_alter_handout_category_alter_handout_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'Author'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='author',
            order_with_respect_to=None,
        ),
    ]
