# Generated by Django 4.2 on 2024-06-21 18:19

from django.db import migrations, models
import django.db.models.deletion
import handout.models


class Migration(migrations.Migration):

    dependencies = [
        ('handout', '0003_alter_author_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=150, verbose_name='author name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(auto_created=True, help_text='کاربران از طریق این لینک به صفحه دسته بندی مورد نظر دسترسی پیدا خواهند کرد', unique=True, verbose_name='access link'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='handout.author', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='category',
            field=models.ManyToManyField(blank=True, to='handout.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='handout',
            name='description',
            field=models.TextField(max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='file',
            field=models.FileField(upload_to='uploads/testAuthor/', validators=[handout.models.validate_file_extension], verbose_name='file to upload'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='file_name',
            field=models.CharField(editable=False, max_length=150, verbose_name='file name'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='file_size',
            field=models.PositiveIntegerField(editable=False, verbose_name='file size'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Handout name'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='page_count',
            field=models.PositiveIntegerField(verbose_name='page count'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='publish_time',
            field=models.DateField(verbose_name='publish date'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='slug',
            field=models.SlugField(auto_created=True, help_text='کاربران از طریق این لینک به صفحه جزوه دسترسی پیدا خواهند کرد', unique=True, verbose_name='access'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='tag',
            field=models.ManyToManyField(blank=True, to='handout.tag', verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, verbose_name='View count'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=150, verbose_name='tag name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(auto_created=True, help_text='کاربران از طریق این لینک به صفحه تگ مورد نظر دسترسی پیدا خواهند کرد', unique=True, verbose_name='access link'),
        ),
    ]
