# Generated by Django 4.2 on 2024-07-18 04:00

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_created_date_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated date'),
        ),
    ]
