# Generated by Django 4.2 on 2024-06-21 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handout', '0005_alter_category_slug_alter_handout_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_ip', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='client_ip')),
                ('handout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handout.handout', verbose_name='handout')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('body', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', verbose_name='status')),
                ('handout', models.ForeignKey(help_text='for wich handout this comment sended?', on_delete=django.db.models.deletion.CASCADE, to='handout.handout', verbose_name='handout')),
            ],
            options={
                'verbose_name_plural': 'Comment',
            },
        ),
    ]
