# Generated by Django 4.2 on 2024-07-16 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handout', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('client_ip', models.GenericIPAddressField(verbose_name='client_ip')),
                ('handout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hlike', to='handout.handout', verbose_name='handout')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('body', models.TextField(verbose_name='Message')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'draft'), (1, 'published'), (2, 'rejected')], default=0, verbose_name='status')),
                ('handout', models.ForeignKey(help_text='for wich handout this comment sended?', on_delete=django.db.models.deletion.CASCADE, related_name='hcomment', to='handout.handout', verbose_name='handout')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'handout'), name='unique_user_handout_like'),
        ),
    ]
