# Generated by Django 4.2 on 2024-07-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('email', 'handout'), name='unique_email_handout_comment'),
        ),
    ]
